### PR TITLE
Add get dependencies

### PR DESCRIPTION
**Pull request by sophia-guo**
Get dependencies from test.dependencies and system.dependencies AdoptOpenJDK jenkins jobs to make the job more stable.

Signed-off-by: Sophia Guo <sophia.gwf@gmail.com>

### CODE REVIEW

**Comment by sophia-guo** [comment]
Function:
https://github.com/sophia-guo/runaqaTest/actions/runs/699897958
System:
https://github.com/sophia-guo/runaqaTest/runs/2224093461?check_suite_focus=true

**Comment by sophia-guo** [comment]
@smlambert Could you please take a look at this? Thanks.

**Review by smlambert — APPROVED** [review]
LGTM, presumably 7z is always present on the runners?

**Comment by sophia-guo** [comment]
I've checked currently supported runners and yes, 7z is pre-installed package or tools. https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software

**Pull request merged**
