### PR TITLE
Add openj9-systemtest repo options

### LINKED ISSUE #94: Add option to pass in openj9 systemtest repo and branch
Currently we are using the default [eclipse-openj9/openj9-systemtest ](https://github.com/eclipse-openj9/openj9-systemtest) to run against openj9 java implementation. It would be nice to add eclipse-openj9/openj9-systemtest  repo and branch as options. So run-aqa action can also be used as the part of eclipse-openj9/openj9-systemtest  developer's PR tests.

### PR DESCRIPTION
**Pull request by Nandini-4120**
## What GitHub issue does this PR apply to?
Resolves #94 

## What changed and why?
Made changes according to the issue description.

### CODE REVIEW

**Comment by Nandini-4120** [comment]
I have made the desired changes and have executed the following command for the Co-author: Somya. Kindly have a look at the commands and suggest if Somya has been added as the Co-author
Screenshot 2021-10-15 at 11 26 56

**Comment by Nandini-4120** [comment]
Hi
Is the PR created by me and Somya(@somya-15) ready to be merged or are there any further changes to be made by us? Please suggest.

**Comment by smlambert** [comment]
Hi @Nandini-4120 - can you please resolve the conflicts in your branch (as some files have changed since you created your PR).  thanks!

**Comment by Nandini-4120** [comment]
Hi 
We have updated the conflicts in our branch. Please suggest.

**Comment by Nandini-4120** [comment]
Hi
We have updated the conflicts in our branch. Please suggest.
The above conflicts that the branch is unrelated as was suggested by you. So kindly have a look if our code can be merged.
Screenshot 2022-01-07 at 14 16 47

**Comment by sophia-guo** [comment]
There are still conflicts need to be resolved.

**Comment by somya-15** [comment]
@sophia-guo, we are unable to identify other conflicts other than system checks. 
Screenshot 2022-01-08 at 12 28 43 AM
 
Kindly guide us in resolving the unidentified conflicts that are causing issues in merging our code. Thanking you.

**Comment by sophia-guo** [comment]
Screen Shot 2022-01-07 at 5 49 15 PM

The conflicts  are between your branch and repo's master branch, which means your branch has to be rebased. The system check is the test failures, which is different from the branch conflicts.

**Comment by smlambert** [comment]
See [Contributing.md](https://github.com/adoptium/aqa-tests/blob/master/Contributing.md) - step 5 for ways to rebase a branch (or reference a git cheat sheet for ways to resolve conflicts in a branch, https://opensource.com/article/20/4/git-merge-conflict).

**Comment by smlambert** [comment]
I will close this PR as stale and it now fails the ECA check because it picks up commits from sophia's old IBM email address which is no longer active.  It also appears to contain merge conflict change lines.

**Pull request closed without merging**
