### PR TITLE
fixes #92 enable jdkRepo

### LINKED ISSUE #92: Add option to support jdk repo and branch
Currently run-aqa run  latest openjdk tests  for all jdks. That is [jdk8](https://github.com/adoptium/jdk8u) for all hotspot jdk8. Similar to all other version and all openj9 jdk. 

It would be nice if we add option to support jdk repo and branch so we can run each jdk's corresponding tests. 

The change would be similar to how we add the openj9 option.

### PR DESCRIPTION
**Pull request by bhuva-v**
fixes https://github.com/adoptium/run-aqa/issues/92

### CODE REVIEW

**Comment by sophia-guo** [comment]
The environment variable is JDK_REPO and JDK_BRANCH

**Review by sophia-guo — APPROVED** [review]
LGTM

**Comment by sophia-guo** [comment]
We will also need to update README. I will create a separate issue.

**Review by smlambert — APPROVED** [review]

**Comment by smlambert** [comment]
PR needs conflicts resolved @bhuva-v are you able to do that, if that is not possible, let's close this PR.  

FYI @sophia-guo

**Comment by karianna** [comment]
@bhuva-v & @sophia-guo - Bump :-)

**Pull request closed without merging**
